apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: codeco

resources:
- rbac.yaml
- configmap.yaml
- secret.yaml
- deployment.yaml

commonLabels:
  app: vk-flightctl-provider
  managed-by: kustomize

images:
- name: vk-flightctl-provider
  newName: quay.io/rh_et_wd/codeco/codeconk8
  newTag: latest
